import Head from 'next/head'
import React from 'react'

const About = () => {
  return (
    <>
        <Head>
        <title>Fernando Henrique | About</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
        </Head>
        <div>index</div>
    </>
  )
}

export default About