import Layout from '@/components/Layout';
import Head from 'next/head';
import Image from 'next/image';
import profilePic from '../../public/images/profile/developer-pic-1.png';
import AnimatedText from '@/components/AnimatedText';
import Link from 'next/link';
import { LinkArrow } from '@/components/Icons';
import HireMe from '@/components/HireMe';
import { userData } from '@/utils/userData';

export default function Home() {
  return (
    <>
      <Head>
        <title>Fernando Henrique</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen">
        <Layout className="pt-0">
          <div className="flex items-center justify-between w-full">
            <div className="w-1/2">
              <Image src={profilePic} alt="CodeBucks" className="w-full h-auto" />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center">
              <AnimatedText text={userData.animatedText} className="!text-6xl !text-left" />
              <p className="my-4 text-base font-medium">{userData.homeSubtitle}</p>
              <div className="flex items-center self-start mt-2">
                <Link
                  href="/Curriculo Fernando.pdf"
                  target="_blank"
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark"
                  download={true}
                >
                  Resume <LinkArrow className={'w-6 ml-3'} />
                </Link>
                <Link href="mailto:fernandogynbsb@gmail.com" target="_blank" className="ml-4 text-lg font-medium capitalize text-dark underline ">
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
      </main>
    </>
  );
}
